# Generated by Django 5.2.7 on 2025-11-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=128)),
                ("type", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("manufacturer", models.TextField(blank=True, default=None, null=True)),
                (
                    "production_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, default=None, null=True)),
                ("distributor", models.TextField(blank=True, default=None, null=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "net_weight",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "quantity_in_package",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Part number of the product, OEM or aftermarket. Stored as text to support alphanumeric values.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "age_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Age rating of the product (e.g., 18 for 18+).",
                        null=True,
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A dictionary for any other relevant metadata.",
                        null=True,
                    ),
                ),
                (
                    "country_of_origin",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("ingredients", models.JSONField(blank=True, default=list, null=True)),
                ("materials", models.JSONField(blank=True, default=list, null=True)),
                ("warnings", models.JSONField(blank=True, default=list, null=True)),
                (
                    "usage_directions",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="discovery.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
